sudo: required
services:
  - docker

env:
  global:
    - RUBY_REPO=$DOCKER_USERNAME/passenger-ruby231
    - RUBY_NODE_REPO=$DOCKER_USERNAME/passenger-ruby231-node670

script:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $RUBY_REPO:$TRAVIS_BUILD_NUMBER -t $RUBY_REPO:$TAG ./client
  - docker build -t $RUBY_NODE_REPO:$TRAVIS_BUILD_NUMBER -t $RUBY_NODE_REPO:$TAG ./server
  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push images to Docker Hub
  - docker push $RUBY_REPO
  - docker push $RUBY_NODE_REPO
