version: '3'
services:
  nginx:
    image: mfarix/passenger-ruby231
    build:
      context: ./Ruby231
      dockerfile: Dockerfile
  api:
    image: mfarix/passenger-ruby231-node670
    build:
      context: ./Ruby231-Node670
      dockerfile: Dockerfile
