version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup custom environment variables
          command: |
            echo 'export RUBY_REPO="$DOCKER_USERNAME/passenger-ruby231"' >> $BASH_ENV
            echo 'export RUBY_NODE_REPO="$DOCKER_USERNAME/passenger-ruby231-node670"' >> $BASH_ENV
      - run:
          name: Build Docker image
          command: |
            source $BASH_ENV
            export TAG=`if [ "$CIRCLE_BRANCH" == "master" ]; then echo "circle-latest"; else echo $CIRCLE_BRANCH ; fi`
            docker build -t $RUBY_REPO:circle-$CIRCLE_BUILD_NUM -t $RUBY_REPO:$TAG ./Ruby231
            docker build -t $RUBY_NODE_REPO:circle-$CIRCLE_BUILD_NUM -t $RUBY_NODE_REPO:$TAG ./Ruby231-Node670
      - deploy:
          name: Push Docker image
          command: |
            source $BASH_ENV
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $RUBY_REPO
            docker push $RUBY_NODE_REPO
workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
